version: '2'

volumes:
  postgres:
  redis:
  minio:
  elasticsearch_development:
  elasticsearch_test:

services:
  app: &bookie
    build: .
    volumes:
      - .:/srv/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - minio
      - elasticsearch_development
      - elasticsearch_test
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      REDIS_URL: redis://redis:6379/1
      SMTP_HOST: maildev
      SMTP_PORT: 25
      S3_URL_HOST: http://localhost:9000
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: accesskey
      S3_SECRET_KEY: secretkey
      ELASTICSEARCH_DEVELOPMENT_URL: http://elastic:changeme@elasticsearch_development:9200
      ELASTICSEARCH_TEST_URL: http://elastic:changeme@elasticsearch_test:9200

  sidekiq:
    <<: *bookie
    ports: []
    depends_on:
      - postgres
      - redis
      - minio
    command: sidekiq

  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:4
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    command: server /root/export
    volumes:
      - minio:/root
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    ports:
      - 9000:9000

  elasticsearch_development: &elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    mem_limit: 1g
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms500m -Xmx500m
    volumes:
      - elasticsearch_development:/usr/share/elasticsearch/data

  elasticsearch_test:
    <<: *elasticsearch
    volumes:
      - elasticsearch_test:/usr/share/elasticsearch/data

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
