version: '2'

volumes:
  bundle:
  postgres:
  minio:

services:
  app:
    build: .
    volumes:
      - .:/home/app/src
      - bundle:/home/app/bundle
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - minio
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      SMTP_HOST: maildev
      SMTP_PORT: 25
      S3_URL_HOST: http://localhost:9000
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: accesskey
      S3_SECRET_KEY: secretkey

  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  minio:
    image: minio/minio
    command: server /root/export
    volumes:
      - minio:/root
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    ports:
      - 9000:9000

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
