indices:
  books:
    settings:
      analysis:
        analyzer:
          isbn:
            tokenizer: 'isbn'
        tokenizer:
          isbn:
            type: 'ngram'
            min_gram: 3
            max_gram: 13
            token_chars:
              - 'digit'
    mappings:
      book:
        properties:
          isbn:
            type: 'text'
            analyzer: 'isbn'
          title:
            type: 'text'
          authors:
            type: 'text'
  users:
    settings:
      analysis:
        analyzer:
          username:
            tokenizer: 'username'
            filter:
              - 'lowercase'
        tokenizer:
          username:
            type: 'edge_ngram'
            min_gram: 1
            max_gram: 25,
            token_chars:
              - 'letter'
              - 'digit'
              - 'punctuation'
              - 'symbol'
    mappings:
      user:
        properties:
          username:
            type: 'text'
            analyzer: 'username'
